# Generated by Django 3.0.10 on 2020-10-21 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='companyadmin',
            managers=[
            ],
        ),
    ]
