# Generated by Django 3.0.10 on 2020-10-22 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20201021_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyadmin',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_admin', to='companies.Company'),
        ),
    ]
